# Generated by Django 4.0.1 on 2022-01-24 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='CreateResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionname', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termname', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_from_prev_term', models.IntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=100)),
                ('classnameI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classI', to='schoolapp.class')),
                ('sessionnameI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessionI', to='schoolapp.currentsession')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=100)),
                ('first_name', models.CharField(max_length=500)),
                ('sur_name', models.CharField(max_length=500)),
                ('other_name', models.CharField(blank=True, max_length=500, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=300)),
                ('date_of_birth', models.DateField()),
                ('date_of_addmission', models.DateField()),
                ('mobile_no', models.IntegerField()),
                ('address', models.TextField(blank=True, null=True)),
                ('others', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectname', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_score', models.IntegerField(blank=True, null=True)),
                ('exem_score', models.IntegerField(blank=True, null=True)),
                ('resultFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentresult', to='schoolapp.createresult')),
                ('subjectCR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentsubject', to='schoolapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=100)),
                ('registeration_number', models.CharField(max_length=1200)),
                ('first_name', models.CharField(max_length=500)),
                ('sur_name', models.CharField(max_length=500)),
                ('other_name', models.CharField(blank=True, max_length=500, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=300)),
                ('date_of_birth', models.DateField()),
                ('date_of_addmission', models.DateField()),
                ('mobile_no', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('others', models.TextField(blank=True, null=True)),
                ('passport', models.ImageField(blank=True, null=True, upload_to='home/images')),
                ('classnameS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classS', to='schoolapp.class')),
            ],
        ),
        migrations.CreateModel(
            name='SessionAndTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionnameSAT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessionSAT', to='schoolapp.currentsession')),
                ('termnameSAT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termSAT', to='schoolapp.currentterm')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date_paid', models.CharField(blank=True, max_length=800, null=True)),
                ('comment', models.CharField(blank=True, max_length=2000, null=True)),
                ('receiptFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiptR', to='schoolapp.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='studentnameI',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentI', to='schoolapp.student'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='termnameI',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termI', to='schoolapp.currentterm'),
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(max_length=400)),
                ('amount', models.IntegerField()),
                ('feeFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceFS', to='schoolapp.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='createresult',
            name='sessionnameCR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessionCR', to='schoolapp.currentsession'),
        ),
        migrations.AddField(
            model_name='createresult',
            name='studentnameCR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stuCR', to='schoolapp.student'),
        ),
        migrations.AddField(
            model_name='createresult',
            name='termnameCR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termCR', to='schoolapp.currentterm'),
        ),
    ]
