# Generated by Django 4.0.1 on 2022-01-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classna',
            field=models.ManyToManyField(to='schoolapp.Class'),
        ),
    ]
