# Generated by Django 4.0.1 on 2022-01-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_student_classna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classna',
        ),
    ]
