# Generated by Django 4.0.1 on 2022-01-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_remove_student_classna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='registeration_number',
            field=models.CharField(max_length=1200, unique=True),
        ),
    ]
