# Generated by Django 4.0.1 on 2022-02-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_alter_student_mobile_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feestructure',
            old_name='amount',
            new_name='feeamount',
        ),
    ]
