# Generated by Django 4.0.1 on 2022-02-08 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_rename_amount_feestructure_feeamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='mobile_no',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{10,15}$')]),
        ),
    ]
